apiVersion: v1
kind: Service
metadata:
    name: backend-lb
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 8080
    selector:
        app: backend

---
apiVersion: v1
kind: Service
metadata:
    name: backend-cip
spec:
    type: ClusterIP
    ports:
    - port: 80
      targetPort: 8080
    selector:
        app: backend
