---
apiVersion: v1
kind: Service
metadata:
    name: backend-cip
spec:
    type: ClusterIP
    ports:
    - port: 8080
    selector:
        app: backend

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: backend-ingress
spec:
  rules:
    - host: backend.azure.com
      http:
        paths:
          - path: /
            backend:
              serviceName: backend-cip
              servicePort: 8080